const demoProducts = [
  {
    id: 1,
    name: '',
    scientificName: '',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
  {
    id: 2,
    name: '',
    scientificName: '',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
  {
    id: 3,
    name: '',
    scientificName: '',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
  {
    id: 4,
    name: '',
    scientificName: '',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
  {
    id: 5,
    name: '',
    scientificName: '',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
  {
    id: 6,
    name: '',
    scientificName: '',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
  {
    id: 7,
    name: '',
    scientificName: '',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
];

export default demoProducts;