const demoCereals = [
  {
    id: 1,
    name: 'Maize',
    scientificName: 'Zea mays',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
  {
    id: 2,
    name: 'Rice',
    scientificName: 'Oryza sativa',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
  {
    id: 3,
    name: 'Millet',
    scientificName: 'Pennisetum glaucum',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
  {
    id: 4,
    name: 'Sorghum',
    scientificName: 'Sorghum bicolor',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
  {
    id: 5,
    name: 'Wheat',
    scientificName: 'Triticum aestivum',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
  {
    id: 6,
    name: 'Barley',
    scientificName: 'Hordeum vulgare',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
  {
    id: 7,
    name: 'Oats',
    scientificName: 'Avena sativa',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
  {
    id: 8,
    name: 'cassava',
    scientificName: 'Manihot esculenta',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
  {
    id: 9,
    name: 'Yam',
    scientificName: 'Dioscorea alata',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
  {
    id: 10,
    name: 'Sweet Potato',
    scientificName: 'Ipomoea batatas',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
  {
    id: 11,
    name: 'Beans',
    scientificName: 'Phaseolus vulgaris',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
  {
    id: 12,
    name: 'Groundnut',
    scientificName: 'Arachis hypogaea',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
  {
    id: 13,
    name: 'Cocoa',
    scientificName: 'Theobroma cacao',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  }
];

export default demoCereals;