const demoLegumes = [
  {
    id: 1,
    name: 'Beans',
    scientificName: 'Phaseolus vulgaris',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
    {
    id: 2,
    name: 'Groundnut',
    scientificName: 'Arachis hypogaea',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
    {
    id: 3,
    name: 'Soybean',
    scientificName: 'Glycine max',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
    },
    {
    id: 4,
    name: 'Cowpea',
    scientificName: 'Vigna unguiculata',
    localName: '',
    location: '',
    grade: '',
    state: '',
    dateHarvested: '',
    sellerContact: '',
  },
]
export default demoLegumes;